function varargout = makeMessage(varargin)
% makeMessage( ... )
% makeMessage( fID, ... )
% makeMessage( printfunc, ... )
% makeMessage( printfunc, fID, ... )
% makeMessage( special, arg );
% makeMessage( special, ... );
% out = makeMessage( ... )
%
% Displays informative messages.
%
% makeMessage is a wrapper to fprintf (or other printers), preponing the output with the name of the caller
%
% INPUT:    printfunc --> if specified, the printer function to be called  [optional, default: fprintf]
%                 fID --> if specified, file ID to be printed to (passed to printer as 1st argument)
%                 ... --> argument list passed to the printer function
% 
%             special --> marker for configuration mode (see below)
%                 arg --> argument for configuration mode
%
% OUTPUT:   out --> output generated by the printer function (only first output argument is returned)
%
% 
% SPECIAL: Configuration can be changed using special keywords starting with '#' as first argument
%     #set_caller_width     --> set minimum field width of caller name to arg
%                               a subsequent call to #set_caller_formatter is necessary to take effect
%     #set_caller_formatter --> set arg to 'centered', 'leftaligned', or 'rightaligned'
%     #set_autonewline      --> set arg to true to emit a newline automatically
%     #nocaller             --> output without emitting caller (e.g. for same-line printing)
%     #raw                  --> no processing of format is done, just forwarding args (incl. fmt) to printer
%
%
% Andreas Sommer, Aug2023, Sep2024, Jun2026
% code@andreas-sommer.eu
%


persistent caller_width  caller_formatter  autonewline

% initialize persistent variables
if isempty(caller_width)    , caller_width = 25; end
if isempty(caller_formatter), caller_formatter = @(caller) caller_formatter_centered(caller, caller_width); end
if isempty(autonewline)     , autonewline = false; end

% collect all input arguments in a (modifiable list)
arglist = varargin;

% internal config
display_caller = true;
rawmode        = false;

% check if first argument is special command
if (nargin >=1) && istext(arglist{1}) && startsWith(arglist{1}, '#')
   switch lower(arglist{1})
      case '#set_caller_width'
         caller_width = arglist{2};
         return
      case '#set_caller_formatter'
         switch(lower(arglist{2}))
            case 'centered'    , caller_formatter = @(caller) caller_formatter_centered(caller, caller_width);
            case 'leftaligned' , caller_formatter = @(caller) caller_formatter_leftaligned(caller, caller_width);
            case 'rightaligned', caller_formatter = @(caller) caller_formatter_rightaligned(caller, caller_width);
            otherwise, error('Unknown caller formatter: %s', arglist{2});
         end
         return
      case '#set_autonewline'
         if arglist{2}, autonewline = true; else, autonewline = false; end
         return
      case '#nocaller'
         display_caller = false;
         arglist = arglist(2:end); % remove special command from argument list
      case '#raw'
         rawmode = true;
         arglist = arglist(2:end); % remove special command from argument list
      otherwise % do nothing as the user might want to output a string starting with #
   end
end


% defaults
default_printer  = @fprintf;
default_fID      = [];
format_processor = @format_processor_default;
output_requested = (nargout > 0);

% get caller first (because makeMessage might call other functions)
if display_caller 
   caller = getCaller(1);  % 1: depth excluding makeMessage itself
else
   caller = '';
end

% 5 cases of calling:
% (1) makeMessage()
% (2) makeMessage(...)
% (3) makeMessage(fID, ...)
% (4) makeMessage(printer, ...)
% (5) makeMessage(printer, fID, ...)
% NOTE:  the makeMessage('#special', ...) is already processed above

% CASE (1):  makeMessage()  --  emit only caller
if (nargin == 0)
   printerargs = {};
   varargout = callPrinter(caller, default_printer, default_fID, printerargs); 
   return; 
end

% Determine type of arg1 and arg2
if (nargin >= 1)
   arg1_is_printer = isa(arglist{1}, 'function_handle');
   arg1_is_fID     = isnumeric(arglist{1});
end
if (nargin >= 2)
   arg2_is_fID  = arg1_is_printer && isnumeric(arglist{2});
else
   arg2_is_fID  = false;
end

% CASE (2):  makeMessage(...)
if ~(arg1_is_printer || arg1_is_fID) && ~arg2_is_fID
   printerargs = arglist;
   varargout = callPrinter(caller, default_printer, default_fID, printerargs);
   return
end

% CASE (3):  makeMessage(fID, ...)
if arg1_is_fID 
   fID = arglist{1};
   if (nargin == 1)
      printerargs = {};
   else
      printerargs = arglist(2:end);
   end
   varargout = callPrinter(caller, default_printer, fID, printerargs);
   return
end

% CASE (4):  makeMessage(printer, ...)
if arg1_is_printer && (~arg2_is_fID)
   printerargs = arglist(2:end);
   varargout = callPrinter(caller, arglist{1}, default_fID, printerargs);
   return
end

% if we reached this point, we are in case (5)

% CASE (5): makeMessage(printer, fID, ...)
printerargs = arglist;
varargout = callPrinter(caller, arglist{1}, arglist{2}, printerargs);

% finito
return

%%% internal helper
   function out = callPrinter(caller, printer, fID, printerargs)
      out = makeMessageInternal(caller, caller_formatter, format_processor, output_requested, printer, fID, printerargs, autonewline, rawmode);
   end

end % of function



%% HELPERS

function out = makeMessageInternal(caller, caller_formatter, format_processor, output_requested, printer, fID, args, autonewline, rawmode)
   % INTERNAL PRINTER  

   % build the format string
   if isempty(args)
      fmt = '';
      args = {};
   elseif ( length(args)==1 )   %#ok<ISCL> - just better to read with length() than isscalar()
      fmt = args{1};
      args = {};
   else
      fmt = args{1};
      args = args(2:end);
   end

   % DEFAULT MODE HERE -- NOT rawmode (in rawmode, we forward fmt and args unmodified to the printer=
   if ~rawmode

      % add caller to format string -- unless caller is empty
      if ~isempty(caller)
         caller = caller_formatter(caller);
      end

      % make/process format string
      fmt = format_processor(fmt, caller);

      % add newline if requested
      if autonewline
         if ~endsWith(fmt, '\n')      % works for strings
            fmt = strcat(fmt, '\n');  % and char arrays
         end
      end

   end % of not in rawmode

   % build the argument list
   if isempty(fID)
      printerargs = [ {fmt} , args];
   else
      printerargs = [ { fID , fmt }, args];
   end

   % corner case everything empty: ensure it's a cell
   if ~iscell(printerargs), printerargs = {}; end

   % try printing
   out = tryPrinting(printer, printerargs, output_requested);

   % invoke the printer - works also if args is (empty) 1x0 cell array
end



function out = tryPrinting(printer, printerargs, output_requested)
   % do the printing and cope for errors
   try
      if (output_requested)
         out = printer(printerargs{:});
         out = {out}; % out becomes varargout
      else
         printer(printerargs{:});
         out = {};    % out becomes varargout
      end
   catch ME
      warning('Printer error.  --  Printer = @%s  --  fID = %g ', func2str(printer), fID)
      rethrow(ME)
   end
end

function fmt = format_processor_default(fmt, caller)
   % DEFAULT FORMAT PROCESSOR
   fmt = convertStringsToChars(fmt);                   % ensure char arrays
   [fmt, newlines] = processBeginningNewlines(fmt);    % emit newlines first, before [caller]
   fmt = sprintf('%s%s%s', newlines, caller, fmt);
end

% CALLER FORMATTERS
function caller = caller_formatter_rightaligned(caller, fieldWidth)
   fmt = '[%*s]  ';
   caller = upper(caller);
   caller = sprintf(fmt, fieldWidth, caller);
end
function caller = caller_formatter_leftaligned(caller, fieldWidth)
   fmt = '[%*s]  ';
   caller = upper(caller);
   caller = sprintf(fmt, -fieldWidth, caller);
end
function caller = caller_formatter_centered(caller, fieldWidth)
   caller = upper(caller);
   caller = sprintf('[%s]  ', centerStr(caller, fieldWidth));
end

% FORMAT HELPERS

function str = centerStr(str, fieldwidth)
   strlen = length(str);
   if strlen > fieldwidth; return; end  % dont touch string if too long
   mid = (fieldwidth - strlen) / 2;
   str = sprintf('%*s%*s', fix(mid)+numel(str), str, ceil(mid), '');
end

function [fmt, newlines] = processBeginningNewlines(fmt)
   newlinecode = '\n';
   newlinecount = 0;
   newlines = '';
   while startsWith(fmt,newlinecode)
      newlinecount = newlinecount + 1;
      fmt(1:2) = [];  % remove '\n' from format -- NOTE: It's a format string, so '\n', not CRLF or LF
      newlines(end+1) = newline(); %#ok<AGROW>   Probably only 1,2,3 times a newline, growing not a problem
   end
end